# -*- coding: utf-8 -*-
"""Assignment7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BujeUaA9QzerDH77RqtDVaMIn8Cwz9h1
"""

import math
from scipy.stats import binom
import matplotlib.pyplot as plt
import array as arr
import numpy as np
import random

x = np.linspace(0, 100, 100) 
fig = plt.figure() 
plt.plot(x, np.exp(-2*x)) 
plt.xlabel("Value of k")
plt.ylabel("Probability density function of variable V")
plt.show()