# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OvK1necbVI4csHWycV6PDXHyM-YfPmQQ
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install functions

import math

p=0.1
#p is the probablity of finding a defective bulb

q=0.9
#q is the probablity of finding a working bulb

N=5
#N is the number of defective bulbs

def nCr(n,r):
    f = math.factorial
    return f(n) / f(r) / f(n-r)

def Binomial_Distribution(x):
  P_x =  nCr(N,x)*(p**x)*(q**(N-x))
  #P_x is the probablity of finding x defective bulbs

  return P_x

print("Probability of finding 0 defective bulbs : ",Binomial_Distribution(0))